apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    tier: backend
spec:
  selector:
    app: nginx
    tier: backend
  type: LoadBalancer 
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 #nginx-deployment.yaml port