apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:      
      containers:
      - name: php
        image: php:8-fpm-alpine
        volumeMounts:
        - name: local-pv-storage
          mountPath: "/usr/share/nginx/html"
        resources: # You need to specify the metric the HPA object will reference
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
      volumes:
      - name: local-pv-storage
        persistentVolumeClaim:
          claimName: local-pv-claim